---
abstract: 'A Perl module for decision-tree based classification of multidimensional data'
author:
  - 'Avinash Kak (kak@purdue.edu)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-DecisionTree
no_index:
  directory:
    - t
    - inc
requires:
  Math::Random: 0.71
version: 2.23
