--- #YAML:1.0
name:               Algorithm-DecisionTree
version:            1.2
abstract:           A pure-Perl implementation for decision-tree based classification of multidimensional data
author:
    - Avinash Kak (kak@purdue.edu)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
